### ISSUE TITLE
Cannot get bot up and running

### ISSUE THREAD

**Issue by athphane** [tropicoo/yt-dlp-bot#130]
Looks like there are some pydantic errors on the repo. Maybe can you freeze your python requirements again so we get correct versions of the packages we need to install. 

Here is a stacktrack from the docker logs

```
yt_bot       | Waiting for RabbitMQ to be reachable on port 5672
yt_bot       | Waiting for PostgreSQL to be reachable on port 5432
yt_bot       | Connection to PostgreSQL on port 5432 verified
yt_bot       | Connection to RabbitMQ on port 5672 verified
yt_bot       | Traceback (most recent call last):
yt_bot       |   File "/app/main.py", line 7, in <module>
yt_bot       |     from bot.core.bot import BotLauncher
yt_bot       |   File "/app/bot/core/bot/__init__.py", line 1, in <module>
yt_bot       |     from bot.core.bot.bot import VideoBot
yt_bot       |   File "/app/bot/core/bot/bot.py", line 8, in <module>
yt_bot       |     from bot.core.config.config import get_main_config
yt_bot       |   File "/app/bot/core/config/__init__.py", line 1, in <module>
yt_bot       |     from bot.core.config.config import settings
yt_bot       |   File "/app/bot/core/config/config.py", line 9, in <module>
yt_bot       |     from yt_shared.config import Settings
yt_bot       |   File "/app/yt_shared/yt_shared/config.py", line 4, in <module>
yt_bot       |     from pydantic import BaseSettings, validator
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pydantic/__init__.py", line 206, in __getattr__
yt_bot       |     return _getattr_migration(attr_name)
yt_bot       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 279, in wrapper
yt_bot       |     raise PydanticImportError(
yt_bot       | pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.
yt_bot       |
yt_bot       | For further information visit https://errors.pydantic.dev/2.0/u/import-error
```

Another one
```
yt_api       | Waiting for RabbitMQ to be reachable on port 5672
yt_api       | Waiting for PostgreSQL to be reachable on port 5432
yt_api       | Connection to RabbitMQ on port 5672 verified
yt_api       | Connection to PostgreSQL on port 5432 verified
yt_api       | Executing <Task finished name='Task-1' coro=<Server.serve() done, defined at /usr/local/lib/python3.11/site-packages/uvicorn/server.py:63> exception=ImportError("cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.11/site-packages/pydantic/fields.py)") created at /usr/local/lib/python3.11/asyncio/runners.py:100> took 0.104 seconds
yt_api       | Traceback (most recent call last):
yt_api       |   File "/usr/local/bin/uvicorn", line 8, in <module>
yt_api       |     sys.exit(main())
yt_api       |              ^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
yt_api       |     return self.main(*args, **kwargs)
yt_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
yt_api       |     rv = self.invoke(ctx)
yt_api       |          ^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
yt_api       |     return ctx.invoke(self.callback, **ctx.params)
yt_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
yt_api       |     return __callback(*args, **kwargs)
yt_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 410, in main
yt_api       |     run(
yt_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 578, in run
yt_api       |     server.run()
yt_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
yt_api       |     return asyncio.run(self.serve(sockets=sockets))
yt_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
yt_api       |     return runner.run(main)
yt_api       |            ^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
yt_api       |     return self._loop.run_until_complete(task)
yt_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
yt_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
yt_api       |     config.load()
yt_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
yt_api       |     self.loaded_app = import_from_string(self.app)
yt_api       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 24, in import_from_string
yt_api       |     raise exc from None
yt_api       |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
yt_api       |     module = importlib.import_module(module_str)
yt_api       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
yt_api       |     return _bootstrap._gcd_import(name[level:], package, level)
yt_api       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
yt_api       |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
yt_api       |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
yt_api       |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
yt_api       |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
yt_api       |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
yt_api       |   File "/app/main.py", line 3, in <module>
yt_api       |     from api.core.app import app  # noqa: F401
yt_api       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_api       |   File "/app/api/core/app.py", line 1, in <module>
yt_api       |     from fastapi import FastAPI
yt_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/__init__.py", line 7, in <module>
yt_api       |     from .applications import FastAPI as FastAPI
yt_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 16, in <module>
yt_api       |     from fastapi import routing
yt_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 22, in <module>
yt_api       |     from fastapi import params
yt_api       |   File "/usr/local/lib/python3.11/site-packages/fastapi/params.py", line 5, in <module>
yt_api       |     from pydantic.fields import FieldInfo, Undefined
yt_api       | ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/usr/local/lib/python3.11/site-packages/pydantic/fields.py)
```

Another one

```
yt_worker    | Waiting for RabbitMQ to be reachable on port 5672
yt_worker    | Waiting for PostgreSQL to be reachable on port 5432
yt_worker    | Connection to RabbitMQ on port 5672 verified
yt_worker    | Connection to PostgreSQL on port 5432 verified
yt_worker    | Traceback (most recent call last):
yt_worker    |   File "/usr/local/bin/alembic", line 8, in <module>
yt_worker    |     sys.exit(main())
yt_worker    |              ^^^^^^
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 632, in main
yt_worker    |     CommandLine(prog=prog).main(argv=argv)
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 626, in main
yt_worker    |     self.run_cmd(cfg, options)
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/alembic/config.py", line 603, in run_cmd
yt_worker    |     fn(
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/alembic/command.py", line 385, in upgrade
yt_worker    |     script.run_env()
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/alembic/script/base.py", line 582, in run_env
yt_worker    |     util.load_python_file(self.dir, "env.py")
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
yt_worker    |     module = load_module_py(module_id, path)
yt_worker    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
yt_worker    |     spec.loader.exec_module(module)  # type: ignore
yt_worker    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_worker    |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
yt_worker    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
yt_worker    |   File "/app/alembic/env.py", line 9, in <module>
yt_worker    |     from yt_shared.config import settings
yt_worker    |   File "/app/yt_shared/yt_shared/config.py", line 4, in <module>
yt_worker    |     from pydantic import BaseSettings, validator
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/pydantic/__init__.py", line 206, in __getattr__
yt_worker    |     return _getattr_migration(attr_name)
yt_worker    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_worker    |   File "/usr/local/lib/python3.11/site-packages/pydantic/_migration.py", line 279, in wrapper
yt_worker    |     raise PydanticImportError(
yt_worker    | pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.0/migration/#basesettings-has-moved-to-pydantic-settings for more details.
yt_worker    |
yt_worker    | For further information visit https://errors.pydantic.dev/2.0/u/import-error
```

**Comment by tropicoo** [comment]
Please update the bot from the git, should work now.
