### ISSUE TITLE
pyrogram.errors.exceptions.bad_request_400.MediaCaptionTooLong

### ISSUE THREAD

**Issue by makusujp** [tropicoo/yt-dlp-bot#163]
the bot went error when error with the video filename is too long.
below is the yt_bot logs output
 ```
2023-08-16 18:35:24,658 - [ERROR] - [SuccessHandler:68] - Upload of "/tmp/download_tmpfs/downloaded/dkft/366997176_1010603666742273_4729472621625809870_n.mp4" failed
2023-08-16 18:35:24 Traceback (most recent call last):
2023-08-16 18:35:24   File "/app/bot/core/handlers/success.py", line 61, in _handle
2023-08-16 18:35:24     await self._create_upload_task(media_object)
2023-08-16 18:35:24   File "/app/bot/core/handlers/success.py", line 86, in _create_upload_task
2023-08-16 18:35:24     await create_task(
2023-08-16 18:35:24 pyrogram.errors.exceptions.bad_request_400.MediaCaptionTooLong: Telegram says: [400 MEDIA_CAPTION_TOO_LONG] - The media caption is too long (caused by "messages.SendMedia")
2023-08-16 18:35:24 2023-08-16 18:35:24,662 - [INFO] - [SuccessHandler:73] - Cleaning up task "48f86114-ebb2-4d33-9dd2-3ea8df547a49": removing download content directory "/tmp/download_tmpfs/downloaded/dkft" with files ['366997176_1010603666742273_4729472621625809870_n.mp4-thumb.jpg', '366997176_1010603666742273_4729472621625809870_n.mp4']

```
⬇️ yt-dlp version: 2023.07.06
🤖 yt-dlp-bot version: 1.4.2

**Comment by makusujp** [comment]
tested on 1.4.3 still get `pyrogram.errors.exceptions.bad_request_400.MediaCaptionTooLong`

**Comment by tropicoo** [comment]
@makusujp The maximum caption length is 1024 characters. The bot will truncate the caption to 1024 symbols if it's higher.
