### ISSUE TITLE
can't running the bot

### ISSUE THREAD

**Issue by yaovenus** [tropicoo/yt-dlp-bot#246]
yt_bot exited with code 1
yt_bot       | [RabbitMQ] Waiting to be reachable on port 5672
yt_bot       | [PostgreSQL] Waiting to be reachable on port 5432
yt_bot       | [RabbitMQ] Connection on port 5672 verified
yt_bot       | [PostgreSQL] Connection on port 5432 verified
yt_bot       | Traceback (most recent call last):
yt_bot       |   File "/app/main.py", line 3, in <module>
yt_bot       |     from api.core.app import app  # noqa: F401
yt_bot       |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
yt_bot       |   File "/app/api/core/app.py", line 10, in <module>
yt_bot       |     from api.core.config import settings
yt_bot       |   File "/app/api/core/config.py", line 10, in <module>
yt_bot       |     settings = ApiSettings()
yt_bot       |                ^^^^^^^^^^^^^
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pydantic_settings/main.py", line 71, in __init__
yt_bot       |     super().__init__(
yt_bot       |   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 171, in __init__
yt_bot       |     self.__pydantic_validator__.validate_python(data, self_instance=self)
yt_bot       | pydantic_core._pydantic_core.ValidationError: 3 validation errors for ApiSettings
yt_bot       | API_HOST
yt_bot       |   Field required [type=missing, input_value={'APPLICATION_NAME': 'yt_...ADED_DIR': 'downloaded'}, input_type=dict]
yt_bot       |     For further information visit https://errors.pydantic.dev/2.6/v/missing
yt_bot       | API_PORT
yt_bot       |   Field required [type=missing, input_value={'APPLICATION_NAME': 'yt_...ADED_DIR': 'downloaded'}, input_type=dict]
yt_bot       |     For further information visit https://errors.pydantic.dev/2.6/v/missing
yt_bot       | API_WORKERS
yt_bot       |   Field required [type=missing, input_value={'APPLICATION_NAME': 'yt_...ADED_DIR': 'downloaded'}, input_type=dict]
yt_bot       |     For further information visit https://errors.pydantic.dev/2.6/v/missing

**Comment by tropicoo** [comment]
Did you delete the `envs/.env_api` file or edit `docker-compose.yaml` file?
Your error says it can't found `API_HOST`, `API_PORT` and `API_WORKERS` variables which are stored `envs/.env_api` file.

**Comment by yaovenus** [comment]
i can't delete the envs/.env_api file and keep defaut。
i can't edit docker-compose.yaml file
